### ISSUE TITLE
User not found

### ISSUE THREAD

**Issue by emimehandjieva** [NikolayIT/GameAITesterOnline#1]
Hello, I have an issue when registering a team - Username "iovigi" could not be found! This http://telerikacademy.com/Users/iovigi is his profile and we'd like to include him in our team. Thank you for the cooperation in advance.
P.S. My profile is emimehandjieva in both github and telerik, in case you need to reach me.

**Comment by NikolayIT** [comment]
He should login to the system in order for you to add him in your team.

**Comment by emimehandjieva** [comment]
Благодаря :)
